/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentSupportRouteImport } from './routes/student.support'
import { Route as StudentStoreRouteImport } from './routes/student.store'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentHealthRouteImport } from './routes/student.health'
import { Route as StudentGroupRouteImport } from './routes/student.group'
import { Route as StudentEvolutionRouteImport } from './routes/student.evolution'
import { Route as StudentCoachCourseRouteImport } from './routes/student.coach-course'
import { Route as StudentChallengeRouteImport } from './routes/student.challenge'
import { Route as StudentBenefitsRouteImport } from './routes/student.benefits'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPatentsRouteImport } from './routes/admin.patents'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDigitalProductsRouteImport } from './routes/admin.digital-products'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminCoachApplicationsRouteImport } from './routes/admin.coach-applications'
import { Route as AdminCoachesInactivityRouteImport } from './routes/admin.coaches.inactivity'
import { Route as ApiOauthGoogleStartRouteImport } from './routes/api.oauth.google.start'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api.oauth.google.callback'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentSupportRoute = StudentSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStoreRoute = StudentStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHealthRoute = StudentHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGroupRoute = StudentGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEvolutionRoute = StudentEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoachCourseRoute = StudentCoachCourseRouteImport.update({
  id: '/coach-course',
  path: '/coach-course',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChallengeRoute = StudentChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBenefitsRoute = StudentBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => StudentRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatentsRoute = AdminPatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDigitalProductsRoute = AdminDigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachApplicationsRoute = AdminCoachApplicationsRouteImport.update({
  id: '/coach-applications',
  path: '/coach-applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesInactivityRoute = AdminCoachesInactivityRouteImport.update({
  id: '/inactivity',
  path: '/inactivity',
  getParentRoute: () => AdminCoachesRoute,
} as any)
const ApiOauthGoogleStartRoute = ApiOauthGoogleStartRouteImport.update({
  id: '/api/oauth/google/start',
  path: '/api/oauth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$code': typeof RCodeRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/coach-applications'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/orders'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/r/$code'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/profile'
    | '/student/store'
    | '/student/support'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/admin/coach-applications'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/orders'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/r/$code'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/profile'
    | '/student/store'
    | '/student/support'
    | '/admin'
    | '/student'
    | '/admin/coaches/inactivity'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/coach-applications'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/orders'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/r/$code'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/profile'
    | '/student/store'
    | '/student/support'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoachRoute: typeof CoachRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  RCodeRoute: typeof RCodeRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthGoogleStartRoute: typeof ApiOauthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/support': {
      id: '/student/support'
      path: '/support'
      fullPath: '/student/support'
      preLoaderRoute: typeof StudentSupportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/store': {
      id: '/student/store'
      path: '/store'
      fullPath: '/student/store'
      preLoaderRoute: typeof StudentStoreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/library': {
      id: '/student/library'
      path: '/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/health': {
      id: '/student/health'
      path: '/health'
      fullPath: '/student/health'
      preLoaderRoute: typeof StudentHealthRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/group': {
      id: '/student/group'
      path: '/group'
      fullPath: '/student/group'
      preLoaderRoute: typeof StudentGroupRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/evolution': {
      id: '/student/evolution'
      path: '/evolution'
      fullPath: '/student/evolution'
      preLoaderRoute: typeof StudentEvolutionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/coach-course': {
      id: '/student/coach-course'
      path: '/coach-course'
      fullPath: '/student/coach-course'
      preLoaderRoute: typeof StudentCoachCourseRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/challenge': {
      id: '/student/challenge'
      path: '/challenge'
      fullPath: '/student/challenge'
      preLoaderRoute: typeof StudentChallengeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/benefits': {
      id: '/student/benefits'
      path: '/benefits'
      fullPath: '/student/benefits'
      preLoaderRoute: typeof StudentBenefitsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patents': {
      id: '/admin/patents'
      path: '/patents'
      fullPath: '/admin/patents'
      preLoaderRoute: typeof AdminPatentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/digital-products': {
      id: '/admin/digital-products'
      path: '/digital-products'
      fullPath: '/admin/digital-products'
      preLoaderRoute: typeof AdminDigitalProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coach-applications': {
      id: '/admin/coach-applications'
      path: '/coach-applications'
      fullPath: '/admin/coach-applications'
      preLoaderRoute: typeof AdminCoachApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches/inactivity': {
      id: '/admin/coaches/inactivity'
      path: '/inactivity'
      fullPath: '/admin/coaches/inactivity'
      preLoaderRoute: typeof AdminCoachesInactivityRouteImport
      parentRoute: typeof AdminCoachesRoute
    }
    '/api/oauth/google/start': {
      id: '/api/oauth/google/start'
      path: '/api/oauth/google/start'
      fullPath: '/api/oauth/google/start'
      preLoaderRoute: typeof ApiOauthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCoachesRouteChildren {
  AdminCoachesInactivityRoute: typeof AdminCoachesInactivityRoute
}

const AdminCoachesRouteChildren: AdminCoachesRouteChildren = {
  AdminCoachesInactivityRoute: AdminCoachesInactivityRoute,
}

const AdminCoachesRouteWithChildren = AdminCoachesRoute._addFileChildren(
  AdminCoachesRouteChildren,
)

interface AdminRouteChildren {
  AdminCoachApplicationsRoute: typeof AdminCoachApplicationsRoute
  AdminCoachesRoute: typeof AdminCoachesRouteWithChildren
  AdminDigitalProductsRoute: typeof AdminDigitalProductsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPatentsRoute: typeof AdminPatentsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoachApplicationsRoute: AdminCoachApplicationsRoute,
  AdminCoachesRoute: AdminCoachesRouteWithChildren,
  AdminDigitalProductsRoute: AdminDigitalProductsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPatentsRoute: AdminPatentsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentBenefitsRoute: typeof StudentBenefitsRoute
  StudentChallengeRoute: typeof StudentChallengeRoute
  StudentCoachCourseRoute: typeof StudentCoachCourseRoute
  StudentEvolutionRoute: typeof StudentEvolutionRoute
  StudentGroupRoute: typeof StudentGroupRoute
  StudentHealthRoute: typeof StudentHealthRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentStoreRoute: typeof StudentStoreRoute
  StudentSupportRoute: typeof StudentSupportRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBenefitsRoute: StudentBenefitsRoute,
  StudentChallengeRoute: StudentChallengeRoute,
  StudentCoachCourseRoute: StudentCoachCourseRoute,
  StudentEvolutionRoute: StudentEvolutionRoute,
  StudentGroupRoute: StudentGroupRoute,
  StudentHealthRoute: StudentHealthRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentStoreRoute: StudentStoreRoute,
  StudentSupportRoute: StudentSupportRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoachRoute: CoachRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  RCodeRoute: RCodeRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthGoogleStartRoute: ApiOauthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
