/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentStoreRouteImport } from './routes/student.store'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentGroupRouteImport } from './routes/student.group'
import { Route as StudentChallengeRouteImport } from './routes/student.challenge'
import { Route as StudentBenefitsRouteImport } from './routes/student.benefits'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPatentsRouteImport } from './routes/admin.patents'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminCoachesInactivityRouteImport } from './routes/admin.coaches.inactivity'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStoreRoute = StudentStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGroupRoute = StudentGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChallengeRoute = StudentChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBenefitsRoute = StudentBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatentsRoute = AdminPatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesInactivityRoute = AdminCoachesInactivityRouteImport.update({
  id: '/inactivity',
  path: '/inactivity',
  getParentRoute: () => AdminCoachesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/group': typeof StudentGroupRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/group': typeof StudentGroupRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/group': typeof StudentGroupRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/store': typeof StudentStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/student'
    | '/admin/coaches'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/group'
    | '/student/profile'
    | '/student/store'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/admin/coaches'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/group'
    | '/student/profile'
    | '/student/store'
    | '/admin'
    | '/student'
    | '/admin/coaches/inactivity'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/pending-approval'
    | '/register'
    | '/student'
    | '/admin/coaches'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/student/benefits'
    | '/student/challenge'
    | '/student/group'
    | '/student/profile'
    | '/student/store'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoachRoute: typeof CoachRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/store': {
      id: '/student/store'
      path: '/store'
      fullPath: '/student/store'
      preLoaderRoute: typeof StudentStoreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/group': {
      id: '/student/group'
      path: '/group'
      fullPath: '/student/group'
      preLoaderRoute: typeof StudentGroupRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/challenge': {
      id: '/student/challenge'
      path: '/challenge'
      fullPath: '/student/challenge'
      preLoaderRoute: typeof StudentChallengeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/benefits': {
      id: '/student/benefits'
      path: '/benefits'
      fullPath: '/student/benefits'
      preLoaderRoute: typeof StudentBenefitsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patents': {
      id: '/admin/patents'
      path: '/patents'
      fullPath: '/admin/patents'
      preLoaderRoute: typeof AdminPatentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches/inactivity': {
      id: '/admin/coaches/inactivity'
      path: '/inactivity'
      fullPath: '/admin/coaches/inactivity'
      preLoaderRoute: typeof AdminCoachesInactivityRouteImport
      parentRoute: typeof AdminCoachesRoute
    }
  }
}

interface AdminCoachesRouteChildren {
  AdminCoachesInactivityRoute: typeof AdminCoachesInactivityRoute
}

const AdminCoachesRouteChildren: AdminCoachesRouteChildren = {
  AdminCoachesInactivityRoute: AdminCoachesInactivityRoute,
}

const AdminCoachesRouteWithChildren = AdminCoachesRoute._addFileChildren(
  AdminCoachesRouteChildren,
)

interface AdminRouteChildren {
  AdminCoachesRoute: typeof AdminCoachesRouteWithChildren
  AdminPatentsRoute: typeof AdminPatentsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoachesRoute: AdminCoachesRouteWithChildren,
  AdminPatentsRoute: AdminPatentsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentBenefitsRoute: typeof StudentBenefitsRoute
  StudentChallengeRoute: typeof StudentChallengeRoute
  StudentGroupRoute: typeof StudentGroupRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentStoreRoute: typeof StudentStoreRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBenefitsRoute: StudentBenefitsRoute,
  StudentChallengeRoute: StudentChallengeRoute,
  StudentGroupRoute: StudentGroupRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentStoreRoute: StudentStoreRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoachRoute: CoachRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
