/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosCompraRouteImport } from './routes/termos-compra'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BecomePartnerRouteImport } from './routes/become-partner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentWorkoutRouteImport } from './routes/student.workout'
import { Route as StudentSupportRouteImport } from './routes/student.support'
import { Route as StudentStoreRouteImport } from './routes/student.store'
import { Route as StudentProtocolRouteImport } from './routes/student.protocol'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProfessionalTrackRouteImport } from './routes/student.professional-track'
import { Route as StudentPartnersRouteImport } from './routes/student.partners'
import { Route as StudentPartnerTrackRouteImport } from './routes/student.partner-track'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentHealthRouteImport } from './routes/student.health'
import { Route as StudentGroupRouteImport } from './routes/student.group'
import { Route as StudentFreebiesRouteImport } from './routes/student.freebies'
import { Route as StudentEvolutionRouteImport } from './routes/student.evolution'
import { Route as StudentCoachCourseRouteImport } from './routes/student.coach-course'
import { Route as StudentChallengeRouteImport } from './routes/student.challenge'
import { Route as StudentCardRouteImport } from './routes/student.card'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentBenefitsRouteImport } from './routes/student.benefits'
import { Route as StudentAssessmentsRouteImport } from './routes/student.assessments'
import { Route as ResultadoTokenRouteImport } from './routes/resultado.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PayOrderNumberRouteImport } from './routes/pay.$orderNumber'
import { Route as PartnerCheckinPartnerIdRouteImport } from './routes/partner-checkin.$partnerId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CheckinStudentIdRouteImport } from './routes/checkin.$studentId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestSalesRouteImport } from './routes/admin.test-sales'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStoreReportsRouteImport } from './routes/admin.store-reports'
import { Route as AdminStoreRouteImport } from './routes/admin.store'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfessionalsRouteImport } from './routes/admin.professionals'
import { Route as AdminProfessionalProductsRouteImport } from './routes/admin.professional-products'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProductOrdersRouteImport } from './routes/admin.product-orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPatentsRouteImport } from './routes/admin.patents'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminPartnerOrdersRouteImport } from './routes/admin.partner-orders'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNutritionistWalletRouteImport } from './routes/admin.nutritionist-wallet'
import { Route as AdminNetworkUnlockHistoryRouteImport } from './routes/admin.network-unlock-history'
import { Route as AdminNetworkUnlockRouteImport } from './routes/admin.network-unlock'
import { Route as AdminNetworkRankingRouteImport } from './routes/admin.network-ranking'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminFreebiesRouteImport } from './routes/admin.freebies'
import { Route as AdminFitmindEventsRouteImport } from './routes/admin.fitmind-events'
import { Route as AdminFinancialSummaryRouteImport } from './routes/admin.financial-summary'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminDigitalProductsRouteImport } from './routes/admin.digital-products'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminCoachReleasesRouteImport } from './routes/admin.coach-releases'
import { Route as AdminCoachIdsRouteImport } from './routes/admin.coach-ids'
import { Route as AdminCoachApplicationsRouteImport } from './routes/admin.coach-applications'
import { Route as AdminChallengeRouteImport } from './routes/admin.challenge'
import { Route as AdminCareerRouteImport } from './routes/admin.career'
import { Route as AdminCalendarsRouteImport } from './routes/admin.calendars'
import { Route as AdminAssessmentDeletionsRouteImport } from './routes/admin.assessment-deletions'
import { Route as AdminAdminWalletRouteImport } from './routes/admin.admin-wallet'
import { Route as AdminAchievementsRouteImport } from './routes/admin.achievements'
import { Route as StudentProfileEditRouteImport } from './routes/student.profile.edit'
import { Route as StudentPartnersPartnerIdRouteImport } from './routes/student.partners.$partnerId'
import { Route as AdminCoachesInactivityRouteImport } from './routes/admin.coaches.inactivity'
import { Route as ApiPublicPayOrderNumberRouteImport } from './routes/api.public.pay.$orderNumber'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api.public.mp.webhook'
import { Route as ApiPublicInviteTokenRouteImport } from './routes/api.public.invite.$token'
import { Route as ApiPublicHooksNetworkUnlockSnapshotRouteImport } from './routes/api/public/hooks/network-unlock-snapshot'
import { Route as ApiPublicCareerResetExpiredRouteImport } from './routes/api/public/career.reset-expired'
import { Route as ApiOauthGoogleStartRouteImport } from './routes/api.oauth.google.start'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api.oauth.google.callback'

const TermosCompraRoute = TermosCompraRouteImport.update({
  id: '/termos-compra',
  path: '/termos-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePartnerRoute = BecomePartnerRouteImport.update({
  id: '/become-partner',
  path: '/become-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentWorkoutRoute = StudentWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSupportRoute = StudentSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStoreRoute = StudentStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProtocolRoute = StudentProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfessionalTrackRoute =
  StudentProfessionalTrackRouteImport.update({
    id: '/professional-track',
    path: '/professional-track',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentPartnersRoute = StudentPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPartnerTrackRoute = StudentPartnerTrackRouteImport.update({
  id: '/partner-track',
  path: '/partner-track',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHealthRoute = StudentHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGroupRoute = StudentGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFreebiesRoute = StudentFreebiesRouteImport.update({
  id: '/freebies',
  path: '/freebies',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEvolutionRoute = StudentEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoachCourseRoute = StudentCoachCourseRouteImport.update({
  id: '/coach-course',
  path: '/coach-course',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChallengeRoute = StudentChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCardRoute = StudentCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBenefitsRoute = StudentBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const ResultadoTokenRoute = ResultadoTokenRouteImport.update({
  id: '/resultado/$token',
  path: '/resultado/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderNumberRoute = PayOrderNumberRouteImport.update({
  id: '/pay/$orderNumber',
  path: '/pay/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCheckinPartnerIdRoute = PartnerCheckinPartnerIdRouteImport.update({
  id: '/partner-checkin/$partnerId',
  path: '/partner-checkin/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinStudentIdRoute = CheckinStudentIdRouteImport.update({
  id: '/checkin/$studentId',
  path: '/checkin/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestSalesRoute = AdminTestSalesRouteImport.update({
  id: '/test-sales',
  path: '/test-sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreReportsRoute = AdminStoreReportsRouteImport.update({
  id: '/store-reports',
  path: '/store-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalsRoute = AdminProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalProductsRoute =
  AdminProfessionalProductsRouteImport.update({
    id: '/professional-products',
    path: '/professional-products',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductOrdersRoute = AdminProductOrdersRouteImport.update({
  id: '/product-orders',
  path: '/product-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatentsRoute = AdminPatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnerOrdersRoute = AdminPartnerOrdersRouteImport.update({
  id: '/partner-orders',
  path: '/partner-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNutritionistWalletRoute = AdminNutritionistWalletRouteImport.update({
  id: '/nutritionist-wallet',
  path: '/nutritionist-wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkUnlockHistoryRoute =
  AdminNetworkUnlockHistoryRouteImport.update({
    id: '/network-unlock-history',
    path: '/network-unlock-history',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNetworkUnlockRoute = AdminNetworkUnlockRouteImport.update({
  id: '/network-unlock',
  path: '/network-unlock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRankingRoute = AdminNetworkRankingRouteImport.update({
  id: '/network-ranking',
  path: '/network-ranking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreebiesRoute = AdminFreebiesRouteImport.update({
  id: '/freebies',
  path: '/freebies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFitmindEventsRoute = AdminFitmindEventsRouteImport.update({
  id: '/fitmind-events',
  path: '/fitmind-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialSummaryRoute = AdminFinancialSummaryRouteImport.update({
  id: '/financial-summary',
  path: '/financial-summary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDigitalProductsRoute = AdminDigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachReleasesRoute = AdminCoachReleasesRouteImport.update({
  id: '/coach-releases',
  path: '/coach-releases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachIdsRoute = AdminCoachIdsRouteImport.update({
  id: '/coach-ids',
  path: '/coach-ids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachApplicationsRoute = AdminCoachApplicationsRouteImport.update({
  id: '/coach-applications',
  path: '/coach-applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerRoute = AdminCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarsRoute = AdminCalendarsRouteImport.update({
  id: '/calendars',
  path: '/calendars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentDeletionsRoute =
  AdminAssessmentDeletionsRouteImport.update({
    id: '/assessment-deletions',
    path: '/assessment-deletions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminWalletRoute = AdminAdminWalletRouteImport.update({
  id: '/admin-wallet',
  path: '/admin-wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const StudentProfileEditRoute = StudentProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudentProfileRoute,
} as any)
const StudentPartnersPartnerIdRoute =
  StudentPartnersPartnerIdRouteImport.update({
    id: '/$partnerId',
    path: '/$partnerId',
    getParentRoute: () => StudentPartnersRoute,
  } as any)
const AdminCoachesInactivityRoute = AdminCoachesInactivityRouteImport.update({
  id: '/inactivity',
  path: '/inactivity',
  getParentRoute: () => AdminCoachesRoute,
} as any)
const ApiPublicPayOrderNumberRoute = ApiPublicPayOrderNumberRouteImport.update({
  id: '/api/public/pay/$orderNumber',
  path: '/api/public/pay/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInviteTokenRoute = ApiPublicInviteTokenRouteImport.update({
  id: '/api/public/invite/$token',
  path: '/api/public/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNetworkUnlockSnapshotRoute =
  ApiPublicHooksNetworkUnlockSnapshotRouteImport.update({
    id: '/api/public/hooks/network-unlock-snapshot',
    path: '/api/public/hooks/network-unlock-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCareerResetExpiredRoute =
  ApiPublicCareerResetExpiredRouteImport.update({
    id: '/api/public/career/reset-expired',
    path: '/api/public/career/reset-expired',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthGoogleStartRoute = ApiOauthGoogleStartRouteImport.update({
  id: '/api/oauth/google/start',
  path: '/api/oauth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-partner': typeof BecomePartnerRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professional': typeof ProfessionalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/termos': typeof TermosRoute
  '/termos-compra': typeof TermosCompraRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/admin-wallet': typeof AdminAdminWalletRoute
  '/admin/assessment-deletions': typeof AdminAssessmentDeletionsRoute
  '/admin/calendars': typeof AdminCalendarsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coach-ids': typeof AdminCoachIdsRoute
  '/admin/coach-releases': typeof AdminCoachReleasesRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/financial-summary': typeof AdminFinancialSummaryRoute
  '/admin/fitmind-events': typeof AdminFitmindEventsRoute
  '/admin/freebies': typeof AdminFreebiesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/network-ranking': typeof AdminNetworkRankingRoute
  '/admin/network-unlock': typeof AdminNetworkUnlockRoute
  '/admin/network-unlock-history': typeof AdminNetworkUnlockHistoryRoute
  '/admin/nutritionist-wallet': typeof AdminNutritionistWalletRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partner-orders': typeof AdminPartnerOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-orders': typeof AdminProductOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/professional-products': typeof AdminProfessionalProductsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/store-reports': typeof AdminStoreReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-sales': typeof AdminTestSalesRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkin/$studentId': typeof CheckinStudentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/partner-checkin/$partnerId': typeof PartnerCheckinPartnerIdRoute
  '/pay/$orderNumber': typeof PayOrderNumberRoute
  '/r/$code': typeof RCodeRoute
  '/resultado/$token': typeof ResultadoTokenRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/card': typeof StudentCardRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/freebies': typeof StudentFreebiesRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/partner-track': typeof StudentPartnerTrackRoute
  '/student/partners': typeof StudentPartnersRouteWithChildren
  '/student/professional-track': typeof StudentProfessionalTrackRoute
  '/student/profile': typeof StudentProfileRouteWithChildren
  '/student/protocol': typeof StudentProtocolRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/student/partners/$partnerId': typeof StudentPartnersPartnerIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/public/career/reset-expired': typeof ApiPublicCareerResetExpiredRoute
  '/api/public/hooks/network-unlock-snapshot': typeof ApiPublicHooksNetworkUnlockSnapshotRoute
  '/api/public/invite/$token': typeof ApiPublicInviteTokenRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/pay/$orderNumber': typeof ApiPublicPayOrderNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-partner': typeof BecomePartnerRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professional': typeof ProfessionalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/termos-compra': typeof TermosCompraRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/admin-wallet': typeof AdminAdminWalletRoute
  '/admin/assessment-deletions': typeof AdminAssessmentDeletionsRoute
  '/admin/calendars': typeof AdminCalendarsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coach-ids': typeof AdminCoachIdsRoute
  '/admin/coach-releases': typeof AdminCoachReleasesRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/financial-summary': typeof AdminFinancialSummaryRoute
  '/admin/fitmind-events': typeof AdminFitmindEventsRoute
  '/admin/freebies': typeof AdminFreebiesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/network-ranking': typeof AdminNetworkRankingRoute
  '/admin/network-unlock': typeof AdminNetworkUnlockRoute
  '/admin/network-unlock-history': typeof AdminNetworkUnlockHistoryRoute
  '/admin/nutritionist-wallet': typeof AdminNutritionistWalletRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partner-orders': typeof AdminPartnerOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-orders': typeof AdminProductOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/professional-products': typeof AdminProfessionalProductsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/store-reports': typeof AdminStoreReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-sales': typeof AdminTestSalesRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkin/$studentId': typeof CheckinStudentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/partner-checkin/$partnerId': typeof PartnerCheckinPartnerIdRoute
  '/pay/$orderNumber': typeof PayOrderNumberRoute
  '/r/$code': typeof RCodeRoute
  '/resultado/$token': typeof ResultadoTokenRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/card': typeof StudentCardRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/freebies': typeof StudentFreebiesRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/partner-track': typeof StudentPartnerTrackRoute
  '/student/partners': typeof StudentPartnersRouteWithChildren
  '/student/professional-track': typeof StudentProfessionalTrackRoute
  '/student/profile': typeof StudentProfileRouteWithChildren
  '/student/protocol': typeof StudentProtocolRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/student/partners/$partnerId': typeof StudentPartnersPartnerIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/public/career/reset-expired': typeof ApiPublicCareerResetExpiredRoute
  '/api/public/hooks/network-unlock-snapshot': typeof ApiPublicHooksNetworkUnlockSnapshotRoute
  '/api/public/invite/$token': typeof ApiPublicInviteTokenRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/pay/$orderNumber': typeof ApiPublicPayOrderNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-partner': typeof BecomePartnerRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professional': typeof ProfessionalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/termos': typeof TermosRoute
  '/termos-compra': typeof TermosCompraRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/admin-wallet': typeof AdminAdminWalletRoute
  '/admin/assessment-deletions': typeof AdminAssessmentDeletionsRoute
  '/admin/calendars': typeof AdminCalendarsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/coach-applications': typeof AdminCoachApplicationsRoute
  '/admin/coach-ids': typeof AdminCoachIdsRoute
  '/admin/coach-releases': typeof AdminCoachReleasesRoute
  '/admin/coaches': typeof AdminCoachesRouteWithChildren
  '/admin/digital-products': typeof AdminDigitalProductsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/financial-summary': typeof AdminFinancialSummaryRoute
  '/admin/fitmind-events': typeof AdminFitmindEventsRoute
  '/admin/freebies': typeof AdminFreebiesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/network-ranking': typeof AdminNetworkRankingRoute
  '/admin/network-unlock': typeof AdminNetworkUnlockRoute
  '/admin/network-unlock-history': typeof AdminNetworkUnlockHistoryRoute
  '/admin/nutritionist-wallet': typeof AdminNutritionistWalletRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partner-orders': typeof AdminPartnerOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/patents': typeof AdminPatentsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/product-orders': typeof AdminProductOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/professional-products': typeof AdminProfessionalProductsRoute
  '/admin/professionals': typeof AdminProfessionalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/store-reports': typeof AdminStoreReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-sales': typeof AdminTestSalesRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkin/$studentId': typeof CheckinStudentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/partner-checkin/$partnerId': typeof PartnerCheckinPartnerIdRoute
  '/pay/$orderNumber': typeof PayOrderNumberRoute
  '/r/$code': typeof RCodeRoute
  '/resultado/$token': typeof ResultadoTokenRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/benefits': typeof StudentBenefitsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/card': typeof StudentCardRoute
  '/student/challenge': typeof StudentChallengeRoute
  '/student/coach-course': typeof StudentCoachCourseRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/freebies': typeof StudentFreebiesRoute
  '/student/group': typeof StudentGroupRoute
  '/student/health': typeof StudentHealthRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/partner-track': typeof StudentPartnerTrackRoute
  '/student/partners': typeof StudentPartnersRouteWithChildren
  '/student/professional-track': typeof StudentProfessionalTrackRoute
  '/student/profile': typeof StudentProfileRouteWithChildren
  '/student/protocol': typeof StudentProtocolRoute
  '/student/store': typeof StudentStoreRoute
  '/student/support': typeof StudentSupportRoute
  '/student/workout': typeof StudentWorkoutRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/coaches/inactivity': typeof AdminCoachesInactivityRoute
  '/student/partners/$partnerId': typeof StudentPartnersPartnerIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/start': typeof ApiOauthGoogleStartRoute
  '/api/public/career/reset-expired': typeof ApiPublicCareerResetExpiredRoute
  '/api/public/hooks/network-unlock-snapshot': typeof ApiPublicHooksNetworkUnlockSnapshotRoute
  '/api/public/invite/$token': typeof ApiPublicInviteTokenRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/pay/$orderNumber': typeof ApiPublicPayOrderNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/become-partner'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/pending-approval'
    | '/privacidade'
    | '/professional'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/termos'
    | '/termos-compra'
    | '/admin/achievements'
    | '/admin/admin-wallet'
    | '/admin/assessment-deletions'
    | '/admin/calendars'
    | '/admin/career'
    | '/admin/challenge'
    | '/admin/coach-applications'
    | '/admin/coach-ids'
    | '/admin/coach-releases'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/financeiro'
    | '/admin/financial-summary'
    | '/admin/fitmind-events'
    | '/admin/freebies'
    | '/admin/library'
    | '/admin/network-ranking'
    | '/admin/network-unlock'
    | '/admin/network-unlock-history'
    | '/admin/nutritionist-wallet'
    | '/admin/orders'
    | '/admin/partner-orders'
    | '/admin/partners'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/product-orders'
    | '/admin/products'
    | '/admin/professional-products'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/store-reports'
    | '/admin/students'
    | '/admin/test-sales'
    | '/admin/users'
    | '/checkin/$studentId'
    | '/invite/$token'
    | '/partner-checkin/$partnerId'
    | '/pay/$orderNumber'
    | '/r/$code'
    | '/resultado/$token'
    | '/student/assessments'
    | '/student/benefits'
    | '/student/calendar'
    | '/student/card'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/freebies'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/partner-track'
    | '/student/partners'
    | '/student/professional-track'
    | '/student/profile'
    | '/student/protocol'
    | '/student/store'
    | '/student/support'
    | '/student/workout'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
    | '/student/partners/$partnerId'
    | '/student/profile/edit'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/public/career/reset-expired'
    | '/api/public/hooks/network-unlock-snapshot'
    | '/api/public/invite/$token'
    | '/api/public/mp/webhook'
    | '/api/public/pay/$orderNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-partner'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/pending-approval'
    | '/privacidade'
    | '/professional'
    | '/register'
    | '/reset-password'
    | '/termos'
    | '/termos-compra'
    | '/admin/achievements'
    | '/admin/admin-wallet'
    | '/admin/assessment-deletions'
    | '/admin/calendars'
    | '/admin/career'
    | '/admin/challenge'
    | '/admin/coach-applications'
    | '/admin/coach-ids'
    | '/admin/coach-releases'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/financeiro'
    | '/admin/financial-summary'
    | '/admin/fitmind-events'
    | '/admin/freebies'
    | '/admin/library'
    | '/admin/network-ranking'
    | '/admin/network-unlock'
    | '/admin/network-unlock-history'
    | '/admin/nutritionist-wallet'
    | '/admin/orders'
    | '/admin/partner-orders'
    | '/admin/partners'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/product-orders'
    | '/admin/products'
    | '/admin/professional-products'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/store-reports'
    | '/admin/students'
    | '/admin/test-sales'
    | '/admin/users'
    | '/checkin/$studentId'
    | '/invite/$token'
    | '/partner-checkin/$partnerId'
    | '/pay/$orderNumber'
    | '/r/$code'
    | '/resultado/$token'
    | '/student/assessments'
    | '/student/benefits'
    | '/student/calendar'
    | '/student/card'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/freebies'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/partner-track'
    | '/student/partners'
    | '/student/professional-track'
    | '/student/profile'
    | '/student/protocol'
    | '/student/store'
    | '/student/support'
    | '/student/workout'
    | '/admin'
    | '/student'
    | '/admin/coaches/inactivity'
    | '/student/partners/$partnerId'
    | '/student/profile/edit'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/public/career/reset-expired'
    | '/api/public/hooks/network-unlock-snapshot'
    | '/api/public/invite/$token'
    | '/api/public/mp/webhook'
    | '/api/public/pay/$orderNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/become-partner'
    | '/coach'
    | '/login'
    | '/onboarding'
    | '/partner'
    | '/pending-approval'
    | '/privacidade'
    | '/professional'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/termos'
    | '/termos-compra'
    | '/admin/achievements'
    | '/admin/admin-wallet'
    | '/admin/assessment-deletions'
    | '/admin/calendars'
    | '/admin/career'
    | '/admin/challenge'
    | '/admin/coach-applications'
    | '/admin/coach-ids'
    | '/admin/coach-releases'
    | '/admin/coaches'
    | '/admin/digital-products'
    | '/admin/financeiro'
    | '/admin/financial-summary'
    | '/admin/fitmind-events'
    | '/admin/freebies'
    | '/admin/library'
    | '/admin/network-ranking'
    | '/admin/network-unlock'
    | '/admin/network-unlock-history'
    | '/admin/nutritionist-wallet'
    | '/admin/orders'
    | '/admin/partner-orders'
    | '/admin/partners'
    | '/admin/patents'
    | '/admin/payments'
    | '/admin/product-orders'
    | '/admin/products'
    | '/admin/professional-products'
    | '/admin/professionals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/admin/store-reports'
    | '/admin/students'
    | '/admin/test-sales'
    | '/admin/users'
    | '/checkin/$studentId'
    | '/invite/$token'
    | '/partner-checkin/$partnerId'
    | '/pay/$orderNumber'
    | '/r/$code'
    | '/resultado/$token'
    | '/student/assessments'
    | '/student/benefits'
    | '/student/calendar'
    | '/student/card'
    | '/student/challenge'
    | '/student/coach-course'
    | '/student/evolution'
    | '/student/freebies'
    | '/student/group'
    | '/student/health'
    | '/student/library'
    | '/student/notifications'
    | '/student/partner-track'
    | '/student/partners'
    | '/student/professional-track'
    | '/student/profile'
    | '/student/protocol'
    | '/student/store'
    | '/student/support'
    | '/student/workout'
    | '/admin/'
    | '/student/'
    | '/admin/coaches/inactivity'
    | '/student/partners/$partnerId'
    | '/student/profile/edit'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/start'
    | '/api/public/career/reset-expired'
    | '/api/public/hooks/network-unlock-snapshot'
    | '/api/public/invite/$token'
    | '/api/public/mp/webhook'
    | '/api/public/pay/$orderNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomePartnerRoute: typeof BecomePartnerRoute
  CoachRoute: typeof CoachRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfessionalRoute: typeof ProfessionalRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TermosRoute: typeof TermosRoute
  TermosCompraRoute: typeof TermosCompraRoute
  CheckinStudentIdRoute: typeof CheckinStudentIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PartnerCheckinPartnerIdRoute: typeof PartnerCheckinPartnerIdRoute
  PayOrderNumberRoute: typeof PayOrderNumberRoute
  RCodeRoute: typeof RCodeRoute
  ResultadoTokenRoute: typeof ResultadoTokenRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthGoogleStartRoute: typeof ApiOauthGoogleStartRoute
  ApiPublicCareerResetExpiredRoute: typeof ApiPublicCareerResetExpiredRoute
  ApiPublicHooksNetworkUnlockSnapshotRoute: typeof ApiPublicHooksNetworkUnlockSnapshotRoute
  ApiPublicInviteTokenRoute: typeof ApiPublicInviteTokenRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicPayOrderNumberRoute: typeof ApiPublicPayOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-compra': {
      id: '/termos-compra'
      path: '/termos-compra'
      fullPath: '/termos-compra'
      preLoaderRoute: typeof TermosCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-partner': {
      id: '/become-partner'
      path: '/become-partner'
      fullPath: '/become-partner'
      preLoaderRoute: typeof BecomePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/workout': {
      id: '/student/workout'
      path: '/workout'
      fullPath: '/student/workout'
      preLoaderRoute: typeof StudentWorkoutRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/support': {
      id: '/student/support'
      path: '/support'
      fullPath: '/student/support'
      preLoaderRoute: typeof StudentSupportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/store': {
      id: '/student/store'
      path: '/store'
      fullPath: '/student/store'
      preLoaderRoute: typeof StudentStoreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/protocol': {
      id: '/student/protocol'
      path: '/protocol'
      fullPath: '/student/protocol'
      preLoaderRoute: typeof StudentProtocolRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/professional-track': {
      id: '/student/professional-track'
      path: '/professional-track'
      fullPath: '/student/professional-track'
      preLoaderRoute: typeof StudentProfessionalTrackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/partners': {
      id: '/student/partners'
      path: '/partners'
      fullPath: '/student/partners'
      preLoaderRoute: typeof StudentPartnersRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/partner-track': {
      id: '/student/partner-track'
      path: '/partner-track'
      fullPath: '/student/partner-track'
      preLoaderRoute: typeof StudentPartnerTrackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/library': {
      id: '/student/library'
      path: '/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/health': {
      id: '/student/health'
      path: '/health'
      fullPath: '/student/health'
      preLoaderRoute: typeof StudentHealthRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/group': {
      id: '/student/group'
      path: '/group'
      fullPath: '/student/group'
      preLoaderRoute: typeof StudentGroupRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/freebies': {
      id: '/student/freebies'
      path: '/freebies'
      fullPath: '/student/freebies'
      preLoaderRoute: typeof StudentFreebiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/evolution': {
      id: '/student/evolution'
      path: '/evolution'
      fullPath: '/student/evolution'
      preLoaderRoute: typeof StudentEvolutionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/coach-course': {
      id: '/student/coach-course'
      path: '/coach-course'
      fullPath: '/student/coach-course'
      preLoaderRoute: typeof StudentCoachCourseRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/challenge': {
      id: '/student/challenge'
      path: '/challenge'
      fullPath: '/student/challenge'
      preLoaderRoute: typeof StudentChallengeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/card': {
      id: '/student/card'
      path: '/card'
      fullPath: '/student/card'
      preLoaderRoute: typeof StudentCardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/benefits': {
      id: '/student/benefits'
      path: '/benefits'
      fullPath: '/student/benefits'
      preLoaderRoute: typeof StudentBenefitsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/resultado/$token': {
      id: '/resultado/$token'
      path: '/resultado/$token'
      fullPath: '/resultado/$token'
      preLoaderRoute: typeof ResultadoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderNumber': {
      id: '/pay/$orderNumber'
      path: '/pay/$orderNumber'
      fullPath: '/pay/$orderNumber'
      preLoaderRoute: typeof PayOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-checkin/$partnerId': {
      id: '/partner-checkin/$partnerId'
      path: '/partner-checkin/$partnerId'
      fullPath: '/partner-checkin/$partnerId'
      preLoaderRoute: typeof PartnerCheckinPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$studentId': {
      id: '/checkin/$studentId'
      path: '/checkin/$studentId'
      fullPath: '/checkin/$studentId'
      preLoaderRoute: typeof CheckinStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-sales': {
      id: '/admin/test-sales'
      path: '/test-sales'
      fullPath: '/admin/test-sales'
      preLoaderRoute: typeof AdminTestSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store-reports': {
      id: '/admin/store-reports'
      path: '/store-reports'
      fullPath: '/admin/store-reports'
      preLoaderRoute: typeof AdminStoreReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professionals': {
      id: '/admin/professionals'
      path: '/professionals'
      fullPath: '/admin/professionals'
      preLoaderRoute: typeof AdminProfessionalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professional-products': {
      id: '/admin/professional-products'
      path: '/professional-products'
      fullPath: '/admin/professional-products'
      preLoaderRoute: typeof AdminProfessionalProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product-orders': {
      id: '/admin/product-orders'
      path: '/product-orders'
      fullPath: '/admin/product-orders'
      preLoaderRoute: typeof AdminProductOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patents': {
      id: '/admin/patents'
      path: '/patents'
      fullPath: '/admin/patents'
      preLoaderRoute: typeof AdminPatentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partner-orders': {
      id: '/admin/partner-orders'
      path: '/partner-orders'
      fullPath: '/admin/partner-orders'
      preLoaderRoute: typeof AdminPartnerOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nutritionist-wallet': {
      id: '/admin/nutritionist-wallet'
      path: '/nutritionist-wallet'
      fullPath: '/admin/nutritionist-wallet'
      preLoaderRoute: typeof AdminNutritionistWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network-unlock-history': {
      id: '/admin/network-unlock-history'
      path: '/network-unlock-history'
      fullPath: '/admin/network-unlock-history'
      preLoaderRoute: typeof AdminNetworkUnlockHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network-unlock': {
      id: '/admin/network-unlock'
      path: '/network-unlock'
      fullPath: '/admin/network-unlock'
      preLoaderRoute: typeof AdminNetworkUnlockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network-ranking': {
      id: '/admin/network-ranking'
      path: '/network-ranking'
      fullPath: '/admin/network-ranking'
      preLoaderRoute: typeof AdminNetworkRankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freebies': {
      id: '/admin/freebies'
      path: '/freebies'
      fullPath: '/admin/freebies'
      preLoaderRoute: typeof AdminFreebiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fitmind-events': {
      id: '/admin/fitmind-events'
      path: '/fitmind-events'
      fullPath: '/admin/fitmind-events'
      preLoaderRoute: typeof AdminFitmindEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial-summary': {
      id: '/admin/financial-summary'
      path: '/financial-summary'
      fullPath: '/admin/financial-summary'
      preLoaderRoute: typeof AdminFinancialSummaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/digital-products': {
      id: '/admin/digital-products'
      path: '/digital-products'
      fullPath: '/admin/digital-products'
      preLoaderRoute: typeof AdminDigitalProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coach-releases': {
      id: '/admin/coach-releases'
      path: '/coach-releases'
      fullPath: '/admin/coach-releases'
      preLoaderRoute: typeof AdminCoachReleasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coach-ids': {
      id: '/admin/coach-ids'
      path: '/coach-ids'
      fullPath: '/admin/coach-ids'
      preLoaderRoute: typeof AdminCoachIdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coach-applications': {
      id: '/admin/coach-applications'
      path: '/coach-applications'
      fullPath: '/admin/coach-applications'
      preLoaderRoute: typeof AdminCoachApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenge': {
      id: '/admin/challenge'
      path: '/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career': {
      id: '/admin/career'
      path: '/career'
      fullPath: '/admin/career'
      preLoaderRoute: typeof AdminCareerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendars': {
      id: '/admin/calendars'
      path: '/calendars'
      fullPath: '/admin/calendars'
      preLoaderRoute: typeof AdminCalendarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessment-deletions': {
      id: '/admin/assessment-deletions'
      path: '/assessment-deletions'
      fullPath: '/admin/assessment-deletions'
      preLoaderRoute: typeof AdminAssessmentDeletionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-wallet': {
      id: '/admin/admin-wallet'
      path: '/admin-wallet'
      fullPath: '/admin/admin-wallet'
      preLoaderRoute: typeof AdminAdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/profile/edit': {
      id: '/student/profile/edit'
      path: '/edit'
      fullPath: '/student/profile/edit'
      preLoaderRoute: typeof StudentProfileEditRouteImport
      parentRoute: typeof StudentProfileRoute
    }
    '/student/partners/$partnerId': {
      id: '/student/partners/$partnerId'
      path: '/$partnerId'
      fullPath: '/student/partners/$partnerId'
      preLoaderRoute: typeof StudentPartnersPartnerIdRouteImport
      parentRoute: typeof StudentPartnersRoute
    }
    '/admin/coaches/inactivity': {
      id: '/admin/coaches/inactivity'
      path: '/inactivity'
      fullPath: '/admin/coaches/inactivity'
      preLoaderRoute: typeof AdminCoachesInactivityRouteImport
      parentRoute: typeof AdminCoachesRoute
    }
    '/api/public/pay/$orderNumber': {
      id: '/api/public/pay/$orderNumber'
      path: '/api/public/pay/$orderNumber'
      fullPath: '/api/public/pay/$orderNumber'
      preLoaderRoute: typeof ApiPublicPayOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invite/$token': {
      id: '/api/public/invite/$token'
      path: '/api/public/invite/$token'
      fullPath: '/api/public/invite/$token'
      preLoaderRoute: typeof ApiPublicInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/network-unlock-snapshot': {
      id: '/api/public/hooks/network-unlock-snapshot'
      path: '/api/public/hooks/network-unlock-snapshot'
      fullPath: '/api/public/hooks/network-unlock-snapshot'
      preLoaderRoute: typeof ApiPublicHooksNetworkUnlockSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/career/reset-expired': {
      id: '/api/public/career/reset-expired'
      path: '/api/public/career/reset-expired'
      fullPath: '/api/public/career/reset-expired'
      preLoaderRoute: typeof ApiPublicCareerResetExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/start': {
      id: '/api/oauth/google/start'
      path: '/api/oauth/google/start'
      fullPath: '/api/oauth/google/start'
      preLoaderRoute: typeof ApiOauthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCoachesRouteChildren {
  AdminCoachesInactivityRoute: typeof AdminCoachesInactivityRoute
}

const AdminCoachesRouteChildren: AdminCoachesRouteChildren = {
  AdminCoachesInactivityRoute: AdminCoachesInactivityRoute,
}

const AdminCoachesRouteWithChildren = AdminCoachesRoute._addFileChildren(
  AdminCoachesRouteChildren,
)

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminAdminWalletRoute: typeof AdminAdminWalletRoute
  AdminAssessmentDeletionsRoute: typeof AdminAssessmentDeletionsRoute
  AdminCalendarsRoute: typeof AdminCalendarsRoute
  AdminCareerRoute: typeof AdminCareerRoute
  AdminChallengeRoute: typeof AdminChallengeRoute
  AdminCoachApplicationsRoute: typeof AdminCoachApplicationsRoute
  AdminCoachIdsRoute: typeof AdminCoachIdsRoute
  AdminCoachReleasesRoute: typeof AdminCoachReleasesRoute
  AdminCoachesRoute: typeof AdminCoachesRouteWithChildren
  AdminDigitalProductsRoute: typeof AdminDigitalProductsRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFinancialSummaryRoute: typeof AdminFinancialSummaryRoute
  AdminFitmindEventsRoute: typeof AdminFitmindEventsRoute
  AdminFreebiesRoute: typeof AdminFreebiesRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminNetworkRankingRoute: typeof AdminNetworkRankingRoute
  AdminNetworkUnlockRoute: typeof AdminNetworkUnlockRoute
  AdminNetworkUnlockHistoryRoute: typeof AdminNetworkUnlockHistoryRoute
  AdminNutritionistWalletRoute: typeof AdminNutritionistWalletRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnerOrdersRoute: typeof AdminPartnerOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPatentsRoute: typeof AdminPatentsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductOrdersRoute: typeof AdminProductOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfessionalProductsRoute: typeof AdminProfessionalProductsRoute
  AdminProfessionalsRoute: typeof AdminProfessionalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminStoreReportsRoute: typeof AdminStoreReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestSalesRoute: typeof AdminTestSalesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminAdminWalletRoute: AdminAdminWalletRoute,
  AdminAssessmentDeletionsRoute: AdminAssessmentDeletionsRoute,
  AdminCalendarsRoute: AdminCalendarsRoute,
  AdminCareerRoute: AdminCareerRoute,
  AdminChallengeRoute: AdminChallengeRoute,
  AdminCoachApplicationsRoute: AdminCoachApplicationsRoute,
  AdminCoachIdsRoute: AdminCoachIdsRoute,
  AdminCoachReleasesRoute: AdminCoachReleasesRoute,
  AdminCoachesRoute: AdminCoachesRouteWithChildren,
  AdminDigitalProductsRoute: AdminDigitalProductsRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFinancialSummaryRoute: AdminFinancialSummaryRoute,
  AdminFitmindEventsRoute: AdminFitmindEventsRoute,
  AdminFreebiesRoute: AdminFreebiesRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminNetworkRankingRoute: AdminNetworkRankingRoute,
  AdminNetworkUnlockRoute: AdminNetworkUnlockRoute,
  AdminNetworkUnlockHistoryRoute: AdminNetworkUnlockHistoryRoute,
  AdminNutritionistWalletRoute: AdminNutritionistWalletRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnerOrdersRoute: AdminPartnerOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPatentsRoute: AdminPatentsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductOrdersRoute: AdminProductOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfessionalProductsRoute: AdminProfessionalProductsRoute,
  AdminProfessionalsRoute: AdminProfessionalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminStoreReportsRoute: AdminStoreReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestSalesRoute: AdminTestSalesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentPartnersRouteChildren {
  StudentPartnersPartnerIdRoute: typeof StudentPartnersPartnerIdRoute
}

const StudentPartnersRouteChildren: StudentPartnersRouteChildren = {
  StudentPartnersPartnerIdRoute: StudentPartnersPartnerIdRoute,
}

const StudentPartnersRouteWithChildren = StudentPartnersRoute._addFileChildren(
  StudentPartnersRouteChildren,
)

interface StudentProfileRouteChildren {
  StudentProfileEditRoute: typeof StudentProfileEditRoute
}

const StudentProfileRouteChildren: StudentProfileRouteChildren = {
  StudentProfileEditRoute: StudentProfileEditRoute,
}

const StudentProfileRouteWithChildren = StudentProfileRoute._addFileChildren(
  StudentProfileRouteChildren,
)

interface StudentRouteChildren {
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentBenefitsRoute: typeof StudentBenefitsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCardRoute: typeof StudentCardRoute
  StudentChallengeRoute: typeof StudentChallengeRoute
  StudentCoachCourseRoute: typeof StudentCoachCourseRoute
  StudentEvolutionRoute: typeof StudentEvolutionRoute
  StudentFreebiesRoute: typeof StudentFreebiesRoute
  StudentGroupRoute: typeof StudentGroupRoute
  StudentHealthRoute: typeof StudentHealthRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPartnerTrackRoute: typeof StudentPartnerTrackRoute
  StudentPartnersRoute: typeof StudentPartnersRouteWithChildren
  StudentProfessionalTrackRoute: typeof StudentProfessionalTrackRoute
  StudentProfileRoute: typeof StudentProfileRouteWithChildren
  StudentProtocolRoute: typeof StudentProtocolRoute
  StudentStoreRoute: typeof StudentStoreRoute
  StudentSupportRoute: typeof StudentSupportRoute
  StudentWorkoutRoute: typeof StudentWorkoutRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentBenefitsRoute: StudentBenefitsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCardRoute: StudentCardRoute,
  StudentChallengeRoute: StudentChallengeRoute,
  StudentCoachCourseRoute: StudentCoachCourseRoute,
  StudentEvolutionRoute: StudentEvolutionRoute,
  StudentFreebiesRoute: StudentFreebiesRoute,
  StudentGroupRoute: StudentGroupRoute,
  StudentHealthRoute: StudentHealthRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPartnerTrackRoute: StudentPartnerTrackRoute,
  StudentPartnersRoute: StudentPartnersRouteWithChildren,
  StudentProfessionalTrackRoute: StudentProfessionalTrackRoute,
  StudentProfileRoute: StudentProfileRouteWithChildren,
  StudentProtocolRoute: StudentProtocolRoute,
  StudentStoreRoute: StudentStoreRoute,
  StudentSupportRoute: StudentSupportRoute,
  StudentWorkoutRoute: StudentWorkoutRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomePartnerRoute: BecomePartnerRoute,
  CoachRoute: CoachRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfessionalRoute: ProfessionalRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TermosRoute: TermosRoute,
  TermosCompraRoute: TermosCompraRoute,
  CheckinStudentIdRoute: CheckinStudentIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  PartnerCheckinPartnerIdRoute: PartnerCheckinPartnerIdRoute,
  PayOrderNumberRoute: PayOrderNumberRoute,
  RCodeRoute: RCodeRoute,
  ResultadoTokenRoute: ResultadoTokenRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthGoogleStartRoute: ApiOauthGoogleStartRoute,
  ApiPublicCareerResetExpiredRoute: ApiPublicCareerResetExpiredRoute,
  ApiPublicHooksNetworkUnlockSnapshotRoute:
    ApiPublicHooksNetworkUnlockSnapshotRoute,
  ApiPublicInviteTokenRoute: ApiPublicInviteTokenRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicPayOrderNumberRoute: ApiPublicPayOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
