
-- Discount Club / Cupons de Desconto
-- Coupons are generated by students for partner discount products.
-- They never expire by time — only by use (status='used' after partner redeems).

CREATE TABLE public.partner_coupons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token varchar(32) NOT NULL UNIQUE,
  partner_id uuid NOT NULL REFERENCES public.partners(id) ON DELETE CASCADE,
  partner_product_id uuid NOT NULL REFERENCES public.partner_products(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  status varchar(12) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','used','cancelled')),
  discount_label text,
  product_name text,
  redeemed_at timestamptz,
  redeemed_by uuid REFERENCES public.profiles(id),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_partner_coupons_partner ON public.partner_coupons(partner_id, status);
CREATE INDEX idx_partner_coupons_student ON public.partner_coupons(student_id, created_at DESC);
CREATE INDEX idx_partner_coupons_product ON public.partner_coupons(partner_product_id);
CREATE UNIQUE INDEX uq_partner_coupons_active_per_student_product
  ON public.partner_coupons(student_id, partner_product_id)
  WHERE status = 'active';

GRANT SELECT, INSERT, UPDATE ON public.partner_coupons TO authenticated;
GRANT ALL ON public.partner_coupons TO service_role;

ALTER TABLE public.partner_coupons ENABLE ROW LEVEL SECURITY;

-- Student can view their own coupons
CREATE POLICY "coupon_student_select" ON public.partner_coupons FOR SELECT
USING (student_id IN (
  SELECT s.id FROM public.students s
  JOIN public.profiles p ON p.id = s.profile_id
  WHERE p.user_id = auth.uid()
));

-- Partner can view coupons issued for their products
CREATE POLICY "coupon_partner_select" ON public.partner_coupons FOR SELECT
USING (partner_id IN (
  SELECT pa.id FROM public.partners pa
  JOIN public.profiles p ON p.id = pa.profile_id
  WHERE p.user_id = auth.uid()
));

-- Admin full access
CREATE POLICY "coupon_admin_all" ON public.partner_coupons FOR ALL
USING (public.is_admin(auth.uid()))
WITH CHECK (public.is_admin(auth.uid()));

-- Student generates a coupon for a discount (free) partner product
CREATE OR REPLACE FUNCTION public.student_generate_partner_coupon(p_partner_product_id uuid)
RETURNS TABLE (coupon_id uuid, token text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_student_id uuid;
  v_partner_id uuid;
  v_product_name text;
  v_existing_id uuid;
  v_existing_token text;
  v_new_token text;
  v_new_id uuid;
BEGIN
  SELECT s.id INTO v_student_id
  FROM students s
  JOIN profiles p ON p.id = s.profile_id
  WHERE p.user_id = auth.uid();

  IF v_student_id IS NULL THEN
    RAISE EXCEPTION 'Apenas alunos podem gerar cupons';
  END IF;

  SELECT pp.partner_id, pp.name INTO v_partner_id, v_product_name
  FROM partner_products pp
  WHERE pp.id = p_partner_product_id
    AND pp.status = 'approved'
    AND pp.is_active_by_partner = true
    AND pp.kind = 'free';

  IF v_partner_id IS NULL THEN
    RAISE EXCEPTION 'Produto de desconto não disponível';
  END IF;

  -- Reuse active coupon if exists
  SELECT id, token INTO v_existing_id, v_existing_token
  FROM partner_coupons
  WHERE student_id = v_student_id
    AND partner_product_id = p_partner_product_id
    AND status = 'active'
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    RETURN QUERY SELECT v_existing_id, v_existing_token;
    RETURN;
  END IF;

  v_new_token := upper(encode(gen_random_bytes(12), 'hex'));

  INSERT INTO partner_coupons (token, partner_id, partner_product_id, student_id, product_name)
  VALUES (v_new_token, v_partner_id, p_partner_product_id, v_student_id, v_product_name)
  RETURNING id INTO v_new_id;

  RETURN QUERY SELECT v_new_id, v_new_token;
END;
$$;

GRANT EXECUTE ON FUNCTION public.student_generate_partner_coupon(uuid) TO authenticated;

-- Partner previews a coupon (no state change)
CREATE OR REPLACE FUNCTION public.partner_preview_coupon(p_token text)
RETURNS TABLE (
  coupon_id uuid,
  status text,
  student_name text,
  student_photo text,
  product_name text,
  created_at timestamptz,
  redeemed_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_partner_id uuid;
BEGIN
  SELECT pa.id INTO v_partner_id
  FROM partners pa
  JOIN profiles p ON p.id = pa.profile_id
  WHERE p.user_id = auth.uid() AND pa.status = 'approved';

  IF v_partner_id IS NULL THEN
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  RETURN QUERY
  SELECT
    pc.id,
    pc.status::text,
    sp.full_name,
    sp.avatar_url,
    pc.product_name,
    pc.created_at,
    pc.redeemed_at
  FROM partner_coupons pc
  JOIN students s ON s.id = pc.student_id
  JOIN profiles sp ON sp.id = s.profile_id
  WHERE pc.token = upper(p_token)
    AND pc.partner_id = v_partner_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.partner_preview_coupon(text) TO authenticated;

-- Partner redeems a coupon (marks as used)
CREATE OR REPLACE FUNCTION public.partner_redeem_coupon(p_token text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_partner_id uuid;
  v_user_profile_id uuid;
  v_coupon_id uuid;
  v_status text;
BEGIN
  SELECT pa.id, p.id INTO v_partner_id, v_user_profile_id
  FROM partners pa
  JOIN profiles p ON p.id = pa.profile_id
  WHERE p.user_id = auth.uid() AND pa.status = 'approved';

  IF v_partner_id IS NULL THEN
    RAISE EXCEPTION 'Acesso negado';
  END IF;

  SELECT id, status INTO v_coupon_id, v_status
  FROM partner_coupons
  WHERE token = upper(p_token) AND partner_id = v_partner_id
  FOR UPDATE;

  IF v_coupon_id IS NULL THEN
    RAISE EXCEPTION 'Cupom não encontrado';
  END IF;

  IF v_status <> 'active' THEN
    RAISE EXCEPTION 'Cupom já utilizado ou cancelado';
  END IF;

  UPDATE partner_coupons
  SET status = 'used',
      redeemed_at = now(),
      redeemed_by = v_user_profile_id
  WHERE id = v_coupon_id;

  RETURN v_coupon_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.partner_redeem_coupon(text) TO authenticated;
