ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS product_type public.product_type DEFAULT 'plan_30',
  ADD COLUMN IF NOT EXISTS min_price DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS max_price DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS is_price_range BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS creator_coach_id UUID REFERENCES public.coaches(id),
  ADD COLUMN IF NOT EXISTS creator_commission_percentage DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nutritionist_fee DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS master_coach_commission DECIMAL(5,2) DEFAULT 10,
  ADD COLUMN IF NOT EXISTS room_rental_commission DECIMAL(5,2) DEFAULT 50,
  ADD COLUMN IF NOT EXISTS course_level INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS course_target VARCHAR(50) DEFAULT 'all',
  ADD COLUMN IF NOT EXISTS profit_percentage_min DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profit_percentage_max DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtitle VARCHAR(255),
  ADD COLUMN IF NOT EXISTS highlights JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS badge_label VARCHAR(50),
  ADD COLUMN IF NOT EXISTS badge_color VARCHAR(20) DEFAULT '#F97316';
ALTER TABLE public.products ALTER COLUMN price DROP NOT NULL;
UPDATE public.products SET status = 'inactive' WHERE slug IS NULL OR slug NOT IN ('inscricao-fitmind','inscricao-premium-fitmind','plano-essencial-30','plano-intermediario-30','plano-avancado-30','plano-black-30','protocolo-transformacao-90','protocolo-elite-90','protocolo-master-90','protocolo-black-90','locacao-sala-fitmind','aulao-fitmind');
UPDATE public.digital_products SET status = 'inactive';
UPDATE public.store_products SET status = 'inactive';
DELETE FROM public.challenge_awards_config;

INSERT INTO public.products (product_type,type,name,slug,subtitle,description,price,duration_days,app_fee,credit_fee_percentage,debit_fee_percentage,pix_fee_percentage,tax_percentage,max_installments,commission_coach,commission_level1,commission_level2,commission_level3,profit_percentage_min,profit_percentage_max,room_rental_commission,feature_benefits_club,feature_class_schedule,feature_weight_tracking,feature_challenge_tracker,feature_winners_forum,feature_awards,feature_coach_chat,feature_group_chat,feature_calorie_ai,feature_photo_evolution,feature_bioimpedance,feature_store,feature_herbalife,highlights,is_featured,badge_label,badge_color,status,sort_order) VALUES
('enrollment','challenge','Inscrição FitMind','inscricao-fitmind','Sua entrada no universo FitMind Club','Inscrição padrão no ecossistema FitMind Club. Dá acesso ao app, ao grupo do desafio e ao acompanhamento do seu coach.',100,NULL,0,2.99,1.69,1.00,6.00,1,100,0,0,0,0,0,50,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,'["Acesso ao app FitMind Club","Vinculação ao seu coach","Acesso ao grupo de suporte","Onboarding personalizado"]',FALSE,'Entrada','#6B7280','active',1),
('enrollment','challenge','Inscrição Premium FitMind','inscricao-premium-fitmind','Inscrição completa com avaliação nutricional','Inscrição premium com consulta nutricional inclusa, avaliação de bioimpedância e clube de benefícios.',285,NULL,20,2.99,1.69,1.00,6.00,3,100,0,0,0,0,0,50,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,'["Tudo da Inscrição Padrão","Consulta nutricional inclusa","Avaliação de bioimpedância","Plano alimentar personalizado","Acesso ao clube de benefícios"]',TRUE,'Premium','#8B5CF6','active',2),
('plan_30','challenge','Plano Essencial 30 Dias','plano-essencial-30','Transformação completa em 30 dias','Plano de acompanhamento intensivo de 30 dias com acesso completo ao app, aulões, acompanhamento do coach e clube de benefícios.',560,30,20,2.99,1.69,1.00,6.00,6,15,8,4,2,15,15,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["30 dias de acompanhamento","Acesso completo ao app","Aulões ao vivo","Clube de benefícios","Avaliação de bioimpedância","Grupo de suporte 24h"]',FALSE,'Essencial','#10B981','active',10),
('plan_30','challenge','Plano Intermediário 30 Dias','plano-intermediario-30','Resultados acelerados com suporte nutricional','Plano completo de 30 dias com suporte nutricional incluso, acompanhamento personalizado e acesso a recursos premium.',860,30,20,2.99,1.69,1.00,6.00,6,30,10,5,2,25,30,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Tudo do Plano Essencial","Suporte nutricional incluso","Check-ins semanais com coach","Plano alimentar personalizado","Análise semanal de progresso","Prioridade nas avaliações"]',FALSE,'Intermediário','#3B82F6','active',11),
('plan_30','challenge','Plano Avançado 30 Dias','plano-avancado-30','Transformação completa com acompanhamento VIP','Acompanhamento diário personalizado, nutrição, treino e suporte total do seu coach.',1300,30,20,2.99,1.69,1.00,6.00,12,40,10,5,3,35,40,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Acompanhamento diário do coach","Nutrição completa inclusa","Treinos personalizados","Videoconferências semanais","Análise de bioimpedância mensal","Acesso vitalício ao conteúdo do mês"]',FALSE,'Avançado','#F59E0B','active',12),
('plan_30','challenge','Plano Black 30 Dias','plano-black-30','A experiência definitiva de transformação','Plano exclusivo com equipe multidisciplinar, acesso irrestrito e resultado garantido.',2000,30,20,2.99,1.69,1.00,6.00,12,50,15,5,3,45,50,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Equipe multidisciplinar dedicada","Coach + Nutricionista + Ed. Físico","Sessões ao vivo ilimitadas","Cardápio semanal personalizado","Treino 100% personalizado","Suporte por WhatsApp 24h","Resultado garantido contratualmente"]',TRUE,'Black','#1A1A1A','active',13),
('protocol_90','challenge','Protocolo Transformação 90 Dias','protocolo-transformacao-90','3 meses de jornada contínua','Protocolo completo de 90 dias para transformação real e duradoura.',2850,90,20,2.99,1.69,1.00,6.00,12,15,8,4,2,15,20,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["3 ciclos de 30 dias","Avaliações mensais de bioimpedância","Ajuste de protocolo a cada fase","Acesso ao app por 90 dias","3 consultas nutricionais","Grupo exclusivo do protocolo"]',FALSE,'Protocolo','#10B981','active',20),
('protocol_90','challenge','Protocolo Elite 90 Dias','protocolo-elite-90','Acompanhamento completo por 3 meses','Protocolo com acompanhamento diário por 90 dias, nutrição, treino e suporte psicológico.',4500,90,20,2.99,1.69,1.00,6.00,12,30,10,5,3,28,35,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Acompanhamento diário","Nutrição + Treino + Saúde Mental","6 avaliações de bioimpedância","Videoconferências quinzenais","Plano alimentar mensal ajustado","Certificado de conclusão"]',FALSE,'Elite','#8B5CF6','active',21),
('protocol_90','challenge','Protocolo Master 90 Dias','protocolo-master-90','A transformação completa que você merece','Protocolo premium com equipe multidisciplinar dedicada por 90 dias.',7500,90,20,2.99,1.69,1.00,6.00,12,40,12,5,3,38,45,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Equipe exclusiva: Coach + Nutri + EF","Acompanhamento 7 dias por semana","Avaliações semanais de progresso","Relatório científico mensal","Acesso a todos os aulões e conteúdos","Convite para evento presencial FitMind"]',TRUE,'Master','#F97316','active',22),
('protocol_90','challenge','Protocolo Black 90 Dias','protocolo-black-90','O protocolo definitivo — exclusivo e ilimitado','Protocolo completo e exclusivo com suporte irrestrito de uma equipe de elite por 90 dias.',13000,90,20,2.99,1.69,1.00,6.00,12,50,15,5,3,48,50,50,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,'["Dedicação exclusiva da equipe","Consultas ilimitadas com especialistas","Acesso a eventos presenciais VIP","Resultado garantido por contrato","Acompanhamento pós-protocolo","Placa de conquista personalizada"]',TRUE,'Black Elite','#0A0A0A','active',23),
('room_rental','physical','Locação de Sala FitMind Center','locacao-sala-fitmind','Espaço profissional para suas consultas e aulas','Alugue uma sala equipada no FitMind Center para atender clientes, dar aulas ou realizar workshops.',NULL,NULL,0,2.99,1.69,1.00,6.00,1,0,0,0,0,0,0,50,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,'["Salas equipadas e climatizadas","Recepção inclusa","Wi-Fi de alta velocidade","Estacionamento","Agendamento pelo app","Coach indicador recebe 50% do 1º aluguel"]',FALSE,'FitMind Center','#0EA5E9','active',30),
('live_class','challenge','Aulão FitMind','aulao-fitmind','Eventos ao vivo com fins lucrativos','Aulões organizados pelos coaches com comissão configurável por evento.',0,1,10,2.99,1.69,1.00,6.00,1,0,0,0,0,0,0,50,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,'["Evento ao vivo presencial ou online","Ingresso com QR Code no app","Lista de participantes automática","Comissão definida por evento","Certificado de participação digital"]',FALSE,'Aulão','#EC4899','active',40)
ON CONFLICT (slug) DO UPDATE SET product_type=EXCLUDED.product_type,type=EXCLUDED.type,name=EXCLUDED.name,subtitle=EXCLUDED.subtitle,description=EXCLUDED.description,price=EXCLUDED.price,duration_days=EXCLUDED.duration_days,app_fee=EXCLUDED.app_fee,credit_fee_percentage=EXCLUDED.credit_fee_percentage,debit_fee_percentage=EXCLUDED.debit_fee_percentage,pix_fee_percentage=EXCLUDED.pix_fee_percentage,tax_percentage=EXCLUDED.tax_percentage,max_installments=EXCLUDED.max_installments,commission_coach=EXCLUDED.commission_coach,commission_level1=EXCLUDED.commission_level1,commission_level2=EXCLUDED.commission_level2,commission_level3=EXCLUDED.commission_level3,profit_percentage_min=EXCLUDED.profit_percentage_min,profit_percentage_max=EXCLUDED.profit_percentage_max,room_rental_commission=EXCLUDED.room_rental_commission,highlights=EXCLUDED.highlights,is_featured=EXCLUDED.is_featured,badge_label=EXCLUDED.badge_label,badge_color=EXCLUDED.badge_color,status=EXCLUDED.status,sort_order=EXCLUDED.sort_order,updated_at=now();
UPDATE public.products SET is_price_range = TRUE, min_price = 20, max_price = 500 WHERE slug = 'aulao-fitmind';

INSERT INTO public.digital_products (type,title,description,instructor,price,original_price,duration_hours,access_days,is_featured,status,sort_order) VALUES
('course','Formação de Coach FitMind — Nível 1','Curso obrigatório para quem quer se tornar coach FitMind Club: fundamentos, produtos, planos, captação, acompanhamento, app, ética e equipe.','Equipe FitMind Club',197,297,8,365,TRUE,'active',1),
('course','Formação de Coach FitMind — Nível 2','Técnicas avançadas de liderança, crescimento de rede MLM, gestão financeira e escala de ganhos.','Equipe FitMind Club',347,497,12,365,FALSE,'active',2),
('course','Formação de Coach FitMind — Nível 3','Formação completa para alcançar patentes de Gerente, Diretor e Master Diretor.','Equipe FitMind Club',597,897,20,365,FALSE,'active',3),
('course','FitMind para Profissionais de Saúde — Módulo Introdutório','Para profissionais de saúde que querem integrar o ecossistema FitMind ao atendimento e gerar renda extra como Master Coach.','Profissionais Certificados FitMind',497,697,10,365,FALSE,'active',10),
('course','Certificação FitMind: Formador de Profissionais de Saúde','Habilita profissionais certificados a ministrar cursos FitMind para outros profissionais da saúde.','Diretores FitMind Club',1497,1997,30,730,FALSE,'active',11);

CREATE TABLE IF NOT EXISTS public.master_coaches (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),coach_id UUID REFERENCES public.coaches(id) NOT NULL UNIQUE,specialty VARCHAR(100),crm_cref VARCHAR(50),bio TEXT,available_for_clients BOOLEAN DEFAULT TRUE,master_commission_percentage DECIMAL(5,2) DEFAULT 10.00,approved_at TIMESTAMPTZ,approved_by UUID REFERENCES public.profiles(id),status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.master_coach_attendances (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),master_coach_id UUID REFERENCES public.master_coaches(id) NOT NULL,student_id UUID REFERENCES public.students(id) NOT NULL,original_coach_id UUID REFERENCES public.coaches(id) NOT NULL,attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,notes TEXT,resulted_in_sale BOOLEAN DEFAULT FALSE,transaction_id UUID REFERENCES public.transactions(id),commission_amount DECIMAL(12,2) DEFAULT 0,commission_status public.commission_status DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.room_rentals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),renter_profile_id UUID REFERENCES public.profiles(id) NOT NULL,referring_coach_id UUID REFERENCES public.coaches(id),room_name VARCHAR(100),rental_date DATE NOT NULL,start_time TIME,end_time TIME,duration_hours DECIMAL(4,2),price_per_hour DECIMAL(8,2),total_amount DECIMAL(12,2),is_first_rental BOOLEAN DEFAULT FALSE,referral_commission_paid BOOLEAN DEFAULT FALSE,referral_commission_amount DECIMAL(12,2) DEFAULT 0,status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.live_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),product_id UUID REFERENCES public.products(id) NOT NULL,organizer_coach_id UUID REFERENCES public.coaches(id) NOT NULL,title VARCHAR(255) NOT NULL,description TEXT,cover_url TEXT,event_date TIMESTAMPTZ NOT NULL,location VARCHAR(255),is_online BOOLEAN DEFAULT FALSE,online_link TEXT,max_participants INTEGER,ticket_price DECIMAL(12,2) NOT NULL,organizer_commission_percentage DECIMAL(5,2) DEFAULT 60.00,platform_fee_percentage DECIMAL(5,2) DEFAULT 20.00,mlm_pool_percentage DECIMAL(5,2) DEFAULT 20.00,status VARCHAR(20) DEFAULT 'upcoming',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.event_tickets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),event_id UUID REFERENCES public.live_events(id) NOT NULL,student_id UUID REFERENCES public.students(id),profile_id UUID REFERENCES public.profiles(id) NOT NULL,referring_coach_id UUID REFERENCES public.coaches(id),ticket_code VARCHAR(20) UNIQUE,qr_code_url TEXT,amount_paid DECIMAL(12,2),payment_method public.payment_method,status VARCHAR(20) DEFAULT 'active',checked_in_at TIMESTAMPTZ,purchased_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.coach_created_courses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),digital_product_id UUID REFERENCES public.digital_products(id) NOT NULL,creator_coach_id UUID REFERENCES public.coaches(id) NOT NULL,creator_commission_percentage DECIMAL(5,2) NOT NULL,upline_commission_percentage DECIMAL(5,2) DEFAULT 0,platform_percentage DECIMAL(5,2) DEFAULT 20.00,approved_by_admin BOOLEAN DEFAULT FALSE,approved_at TIMESTAMPTZ,status VARCHAR(20) DEFAULT 'pending_approval',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS public.course_teacher_commissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),digital_product_id UUID REFERENCES public.digital_products(id) NOT NULL,teacher_profile_id UUID REFERENCES public.profiles(id) NOT NULL,commission_percentage DECIMAL(5,2) NOT NULL,is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE public.commissions ADD COLUMN IF NOT EXISTS is_master_coach_commission BOOLEAN DEFAULT FALSE;
ALTER TABLE public.commissions ADD COLUMN IF NOT EXISTS master_coach_id UUID REFERENCES public.master_coaches(id);

ALTER TABLE public.master_coaches ENABLE ROW LEVEL SECURITY; ALTER TABLE public.master_coach_attendances ENABLE ROW LEVEL SECURITY; ALTER TABLE public.room_rentals ENABLE ROW LEVEL SECURITY; ALTER TABLE public.live_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.event_tickets ENABLE ROW LEVEL SECURITY; ALTER TABLE public.coach_created_courses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.course_teacher_commissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS master_coaches_admin_all ON public.master_coaches; CREATE POLICY master_coaches_admin_all ON public.master_coaches FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS master_coaches_read_active ON public.master_coaches; CREATE POLICY master_coaches_read_active ON public.master_coaches FOR SELECT USING (status = 'active');
DROP POLICY IF EXISTS master_attendances_admin_all ON public.master_coach_attendances; CREATE POLICY master_attendances_admin_all ON public.master_coach_attendances FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS room_rentals_admin_all ON public.room_rentals; CREATE POLICY room_rentals_admin_all ON public.room_rentals FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS room_rentals_own_read ON public.room_rentals; CREATE POLICY room_rentals_own_read ON public.room_rentals FOR SELECT USING (renter_profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()) OR EXISTS (SELECT 1 FROM public.coaches c JOIN public.profiles p ON p.id=c.profile_id WHERE p.user_id=auth.uid() AND c.id=referring_coach_id));
DROP POLICY IF EXISTS live_events_admin_all ON public.live_events; CREATE POLICY live_events_admin_all ON public.live_events FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS live_events_read_upcoming ON public.live_events; CREATE POLICY live_events_read_upcoming ON public.live_events FOR SELECT USING (status IN ('upcoming','active'));
DROP POLICY IF EXISTS live_events_coach_manage ON public.live_events; CREATE POLICY live_events_coach_manage ON public.live_events FOR ALL USING (EXISTS (SELECT 1 FROM public.coaches c JOIN public.profiles p ON p.id=c.profile_id WHERE p.user_id=auth.uid() AND c.id=organizer_coach_id)) WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c JOIN public.profiles p ON p.id=c.profile_id WHERE p.user_id=auth.uid() AND c.id=organizer_coach_id));
DROP POLICY IF EXISTS event_tickets_admin_all ON public.event_tickets; CREATE POLICY event_tickets_admin_all ON public.event_tickets FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS event_tickets_own_read ON public.event_tickets; CREATE POLICY event_tickets_own_read ON public.event_tickets FOR SELECT USING (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()));
DROP POLICY IF EXISTS coach_created_courses_admin_all ON public.coach_created_courses; CREATE POLICY coach_created_courses_admin_all ON public.coach_created_courses FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS coach_created_courses_public_read ON public.coach_created_courses; CREATE POLICY coach_created_courses_public_read ON public.coach_created_courses FOR SELECT USING (status = 'active' AND approved_by_admin = TRUE);
DROP POLICY IF EXISTS course_teacher_commissions_admin_all ON public.course_teacher_commissions; CREATE POLICY course_teacher_commissions_admin_all ON public.course_teacher_commissions FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS course_teacher_commissions_own_read ON public.course_teacher_commissions; CREATE POLICY course_teacher_commissions_own_read ON public.course_teacher_commissions FOR SELECT USING (teacher_profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()) OR public.is_admin(auth.uid()));

CREATE OR REPLACE VIEW public.product_commission_preview AS SELECT p.id,p.name,p.product_type,p.price,p.app_fee,p.nutritionist_fee,p.tax_percentage,p.pix_fee_percentage,p.credit_fee_percentage,p.debit_fee_percentage,ROUND(p.price*p.pix_fee_percentage/100,2) AS pix_gateway_fee,ROUND((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.pix_fee_percentage/100))*p.tax_percentage/100,2) AS pix_tax,ROUND(p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.pix_fee_percentage/100)-((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.pix_fee_percentage/100))*p.tax_percentage/100),2) AS pix_commission_base,ROUND((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.pix_fee_percentage/100)-((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.pix_fee_percentage/100))*p.tax_percentage/100))*p.commission_coach/100,2) AS pix_coach_commission,ROUND(p.price*p.credit_fee_percentage/100,2) AS credit_gateway_fee,ROUND((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.credit_fee_percentage/100))*p.tax_percentage/100,2) AS credit_tax,ROUND((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.credit_fee_percentage/100)-((p.price-p.app_fee-COALESCE(p.nutritionist_fee,0)-(p.price*p.credit_fee_percentage/100))*p.tax_percentage/100))*p.commission_coach/100,2) AS credit_coach_commission,p.commission_coach,p.commission_level1,p.commission_level2,p.commission_level3 FROM public.products p WHERE p.status='active' AND p.price IS NOT NULL AND p.price>0;
INSERT INTO public.app_settings (key,value,description) VALUES ('student_nav_order','home,challenge,group,store,courses,benefits,profile','Ordem dos itens no menu inferior do aluno'),('student_home_layout','default','Layout padrão da home do aluno'),('student_store_layout','catalog','Layout padrão da loja do aluno'),('student_benefits_layout','tabs','Layout padrão da aba benefícios'),('product_default_app_fee','20','Taxa app padrão'),('product_default_pix_fee','1.00','Taxa PIX padrão'),('product_default_debit_fee','1.69','Taxa débito padrão'),('product_default_credit_fee','2.99','Taxa crédito padrão'),('product_default_tax','6.00','Imposto padrão'),('product_default_max_installments','12','Parcelas máximas padrão'),('master_coach_default_commission','10.00','Comissão padrão de Master Coach'),('master_coach_requires_approval','true','Exige aprovação de Master Coach'),('room_first_rental_commission','50.00','Comissão do primeiro aluguel de sala'),('coach_required_course','Formação de Coach FitMind — Nível 1','Curso obrigatório para virar coach'),('coach_course_completion_required','true','Exige concluir curso antes de criar conta coach'),('certified_teacher_commission','30.00','Comissão de professores certificados'),('live_event_organizer_percentage','60.00','Percentual do organizador em aulões'),('live_event_platform_percentage','20.00','Percentual da plataforma em aulões'),('live_event_mlm_percentage','20.00','Percentual da rede em aulões') ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,description=EXCLUDED.description,updated_at=now();
CREATE INDEX IF NOT EXISTS idx_products_product_type ON public.products(product_type); CREATE INDEX IF NOT EXISTS idx_live_events_status_date ON public.live_events(status,event_date); CREATE INDEX IF NOT EXISTS idx_event_tickets_profile ON public.event_tickets(profile_id); CREATE INDEX IF NOT EXISTS idx_room_rentals_profile ON public.room_rentals(renter_profile_id);