INSERT INTO public.exercise_library (name, muscle_group, equipment, difficulty, body_focus, is_global, media_type) VALUES
('Agachamento Livre','Pernas','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Agachamento com Salto','Pernas','Peso corporal','intermediario','Membros inferiores',true,'video'),
('Agachamento Sumô','Pernas / Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Agachamento Sumô com Halteres','Pernas / Glúteos','Halteres','intermediario','Membros inferiores',true,'video'),
('Agachamento Isométrico na Parede','Pernas','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Agachamento com Pausa','Pernas','Peso corporal','intermediario','Membros inferiores',true,'video'),
('Agachamento Explosivo','Pernas','Peso corporal','avancado','Membros inferiores',true,'video'),
('Agachamento Hack','Pernas','Máquina Hack','intermediario','Membros inferiores',true,'video'),
('Agachamento Smith','Pernas','Smith','intermediario','Membros inferiores',true,'video'),
('Afundo Alternado','Pernas / Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Afundo Reverso','Pernas / Glúteos','Peso corporal','intermediario','Membros inferiores',true,'video'),
('Elevação Pélvica','Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Elevação Pélvica Unilateral','Glúteos','Peso corporal','intermediario','Membros inferiores',true,'video'),
('Elevação Pélvica no Solo','Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Elevação Pélvica na Máquina','Glúteos','Máquina','intermediario','Membros inferiores',true,'video'),
('Ponte para Glúteos','Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Ponte Unilateral','Glúteos','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Stiff Unilateral (peso corporal)','Posterior de coxa','Peso corporal','intermediario','Membros inferiores',true,'video'),
('Stiff','Posterior de coxa','Barra/Halteres','intermediario','Membros inferiores',true,'video'),
('Levantamento Terra','Posterior / Costas','Barra','avancado','Corpo inteiro',true,'video'),
('Panturrilha em Pé','Panturrilha','Peso corporal','iniciante','Membros inferiores',true,'video'),
('Panturrilha na Máquina','Panturrilha','Máquina','iniciante','Membros inferiores',true,'video'),
('Leg Press','Pernas','Leg Press','iniciante','Membros inferiores',true,'video'),
('Cadeira Extensora','Quadríceps','Máquina','iniciante','Membros inferiores',true,'video'),
('Cadeira Flexora','Posterior','Máquina','iniciante','Membros inferiores',true,'video'),
('Mesa Flexora','Posterior','Máquina','iniciante','Membros inferiores',true,'video'),
('Cadeira Abdutora','Glúteos','Máquina','iniciante','Membros inferiores',true,'video'),
('Cadeira Adutora','Adutores','Máquina','iniciante','Membros inferiores',true,'video'),
('Superman no Solo','Lombar / Costas','Peso corporal','iniciante','Core / Costas',true,'video'),
('Remada Isométrica com Toalha','Costas','Toalha','iniciante','Membros superiores',true,'video'),
('Puxada Alta','Costas','Polia','intermediario','Membros superiores',true,'video'),
('Pull Down','Costas','Polia','intermediario','Membros superiores',true,'video'),
('Remada Curvada','Costas','Barra/Halter','intermediario','Membros superiores',true,'video'),
('Pullover','Costas','Halter/Polia','intermediario','Membros superiores',true,'video'),
('Remada com Halter','Costas','Halter','intermediario','Membros superiores',true,'video'),
('Crucifixo Invertido na Máquina','Costas / Posterior de ombro','Máquina','intermediario','Membros superiores',true,'video'),
('Rosca Direta na Máquina','Bíceps','Máquina','iniciante','Membros superiores',true,'video'),
('Rosca Martelo','Bíceps','Halteres','iniciante','Membros superiores',true,'video'),
('Flexão de Braço','Peito / Tríceps','Peso corporal','intermediario','Membros superiores',true,'video'),
('Flexão de Braço Tradicional','Peito / Tríceps','Peso corporal','intermediario','Membros superiores',true,'video'),
('Flexão de Braço com Apoio','Peito / Tríceps','Peso corporal','iniciante','Membros superiores',true,'video'),
('Flexão de Braço com Pausa','Peito / Tríceps','Peso corporal','intermediario','Membros superiores',true,'video'),
('Flexão Explosiva','Peito / Tríceps','Peso corporal','avancado','Membros superiores',true,'video'),
('Flexão Isométrica','Peito / Tríceps','Peso corporal','intermediario','Membros superiores',true,'video'),
('Supino Reto','Peito','Barra/Halteres','intermediario','Membros superiores',true,'video'),
('Supino Inclinado','Peito','Barra/Halteres','intermediario','Membros superiores',true,'video'),
('Crucifixo na Máquina','Peito','Máquina','iniciante','Membros superiores',true,'video'),
('Desenvolvimento na Máquina','Ombros','Máquina','intermediario','Membros superiores',true,'video'),
('Elevação Frontal','Ombros','Halteres','iniciante','Membros superiores',true,'video'),
('Elevação Lateral','Ombros','Halteres','iniciante','Membros superiores',true,'video'),
('Elevação Frontal Isométrica','Ombros','Peso corporal/Halteres','iniciante','Membros superiores',true,'video'),
('Tríceps no Banco ou Cadeira','Tríceps','Banco','intermediario','Membros superiores',true,'video'),
('Tríceps na Máquina','Tríceps','Máquina','iniciante','Membros superiores',true,'video'),
('Tríceps Corda','Tríceps','Polia','intermediario','Membros superiores',true,'video'),
('Tríceps Testa com Halter','Tríceps','Halter','intermediario','Membros superiores',true,'video'),
('Prancha Ventral','Core','Peso corporal','iniciante','Core / Costas',true,'video'),
('Prancha Lateral','Core','Peso corporal','iniciante','Core / Costas',true,'video'),
('Prancha com Toque no Ombro','Core','Peso corporal','intermediario','Core / Costas',true,'video'),
('Abdominal Supra','Abdômen','Peso corporal','iniciante','Core / Costas',true,'video'),
('Abdominal Infra','Abdômen','Peso corporal','iniciante','Core / Costas',true,'video'),
('Abdominal Bicicleta','Abdômen','Peso corporal','iniciante','Core / Costas',true,'video'),
('Abdominal na Máquina','Abdômen','Máquina','iniciante','Core / Costas',true,'video'),
('Burpee','Corpo inteiro','Peso corporal','avancado','Corpo inteiro',true,'video'),
('Burpee Adaptado','Corpo inteiro','Peso corporal','intermediario','Corpo inteiro',true,'video'),
('Mountain Climber','Core / Cardio','Peso corporal','intermediario','Corpo inteiro',true,'video'),
('Escalada','Cardio / Core','Peso corporal','intermediario','Corpo inteiro',true,'video'),
('Poli-Chinelo','Cardio','Peso corporal','intermediario','Cardio',true,'video'),
('Corrida estacionada','Cardio','Peso corporal','iniciante','Cardio',true,'video'),
('Corrida no Lugar','Cardio','Peso corporal','iniciante','Cardio',true,'video'),
('Corrida leve/moderada','Cardio','—','iniciante','Cardio',true,'video'),
('Caminhada acelerada','Cardio','—','iniciante','Cardio',true,'video'),
('Caminhada inclinada na esteira','Cardio','Esteira','iniciante','Cardio',true,'video'),
('Esteira inclinada','Cardio','Esteira','intermediario','Cardio',true,'video'),
('Escadas','Cardio','—','intermediario','Cardio',true,'video'),
('Subida de escadas','Cardio','—','intermediario','Cardio',true,'video'),
('Subida de escada ou corrida estacionada','Cardio','—','iniciante','Cardio',true,'video'),
('Subir e descer escadas','Cardio','—','iniciante','Cardio',true,'video'),
('Elíptico','Cardio','Elíptico','iniciante','Cardio',true,'video'),
('Bicicleta Horizontal','Cardio','Bicicleta','iniciante','Cardio',true,'video');